# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FatalAccident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccdType', models.CharField(default='Fatal', editable=False, max_length=30, verbose_name='Accident Type')),
                ('UnitName', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('TypeOfEmployee', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], default='Regular', max_length=10, verbose_name='Employee Type')),
                ('EmployeeID', models.CharField(max_length=20, verbose_name='Employee ID')),
                ('EmployeeName', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('Department', models.CharField(max_length=20)),
                ('Shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'G')], default='A', max_length=20)),
                ('Cause', models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], default='Slip', max_length=100)),
                ('BriefAccount', models.TextField(verbose_name='Narrative')),
                ('LearningPoint', models.CharField(max_length=50, verbose_name='Learning Point')),
            ],
        ),
        migrations.CreateModel(
            name='FirstAid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccdType', models.CharField(default='First-Aid', editable=False, max_length=30, verbose_name='Accident Type')),
                ('UnitName', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('TypeOfEmployee', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], default='Regular', max_length=10, verbose_name='Employee Type')),
                ('EmployeeID', models.CharField(max_length=20, verbose_name='Employee ID')),
                ('EmployeeName', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('Department', models.CharField(max_length=20)),
                ('Shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'G')], default='A', max_length=20)),
                ('Cause', models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], default='Slip', max_length=100)),
                ('BriefAccount', models.TextField(verbose_name='Narrative')),
            ],
        ),
        migrations.CreateModel(
            name='NonReportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccdType', models.CharField(default='Non-Reportable', editable=False, max_length=30, verbose_name='Accident Type')),
                ('UnitName', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('TypeOfEmployee', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], default='Regular', max_length=10, verbose_name='Employee Type')),
                ('EmployeeID', models.CharField(max_length=20, verbose_name='Employee ID')),
                ('EmployeeName', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('Department', models.CharField(max_length=20)),
                ('Shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'G')], default='A', max_length=20)),
                ('Cause', models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], default='Slip', max_length=100)),
                ('BriefAccount', models.TextField(verbose_name='Narrative')),
            ],
        ),
        migrations.CreateModel(
            name='Reportable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccdType', models.CharField(default='Reportable', editable=False, max_length=30, verbose_name='Accident Type')),
                ('UnitName', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('TypeOfEmployee', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], default='Regular', max_length=10, verbose_name='Employee Type')),
                ('EmployeeID', models.CharField(max_length=20, verbose_name='Employee ID')),
                ('EmployeeName', models.CharField(max_length=30, verbose_name='Employee Name')),
                ('Department', models.CharField(max_length=20)),
                ('Shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'G')], default='A', max_length=20)),
                ('Cause', models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], default='Slip', max_length=100)),
                ('BriefAccount', models.TextField(verbose_name='Narrative')),
            ],
        ),
    ]
