# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0002_auto_20170807_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllAccident',
            fields=[
                ('UnitName', models.CharField(db_column='unit_name', max_length=30, verbose_name='Unit Name')),
                ('AccdId', models.OneToOneField(db_column='accd_id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='InputForms.accd_details', verbose_name='Accident ID')),
                ('AccdType', models.CharField(choices=[('Fatal', 'Fatal'), ('Reportable', 'Reportable'), ('Non-Reportable', 'Non-Reportable'), ('First-Aid', 'First-Aid')], db_column='accd_type', default='Fatal', max_length=30, verbose_name='Accident Type')),
                ('Date', models.DateField()),
                ('Time', models.TimeField()),
                ('EmpName', models.CharField(db_column='emp_name', max_length=30, verbose_name='Employee Name')),
                ('EmpType', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], db_column='emp_type', default='Regular', max_length=10, verbose_name='Employee Type')),
                ('Department', models.CharField(db_column='dept', max_length=20)),
                ('Shift', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('G', 'G')], db_column='shift', default='A', max_length=20)),
                ('Cause', models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], db_column='cause', default='Slip', max_length=100)),
                ('Narrative', models.TextField(db_column='narrative', verbose_name='Narrative')),
                ('LearningPoint', models.CharField(blank=True, db_column='learning_point', max_length=50, verbose_name='Learning Point')),
            ],
            options={
                'db_table': 'emp_accd_view',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='accd_details',
            name='cause',
            field=models.CharField(choices=[('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed')], default='Slip', max_length=100, verbose_name='Accident Cause'),
        ),
    ]
