# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0003_auto_20170821_1915'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accd_details',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='accd_details',
            name='Time',
        ),
        migrations.AddField(
            model_name='accd_details',
            name='DateTime',
            field=models.DateTimeField(default=datetime.datetime(2017, 9, 22, 12, 1, 47, 555000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
