# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-22 13:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0004_auto_20170922_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accd_details',
            name='DateTime',
        ),
        migrations.AddField(
            model_name='accd_details',
            name='Date',
            field=models.DateField(default=datetime.date(2017, 9, 22)),
        ),
        migrations.AddField(
            model_name='accd_details',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
