# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-23 02:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0005_auto_20170922_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accd_details',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='accd_details',
            name='Time',
        ),
        migrations.AddField(
            model_name='accd_details',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
    ]
