# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 03:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0006_auto_20170923_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accd_details',
            name='cause',
            field=models.CharField(choices=[('Common Causes:', (('Fall of material', 'Fall of material'), ('Material handling', 'Material handling'), ('Road incident', 'Road incident'), ('Slip', 'Slip'), ('Fall of person', 'Fall of person'), ('Burn', 'Burn'), ('Electrocution', 'Electrocution'), ('Gas exposure', 'Gas exposure'), ('Hit/Caught/Pressed', 'Hit/Caught/Pressed'))), ('Others:', (('Violation of SOPs', 'Violation of SOPs'), ('Violation of SMPs', 'Violation of SMPs'), ('BBS Aspects', 'BBS Aspects'), ('Equipment Failure', 'Equipment Failure')))], default='Slip', max_length=100, verbose_name='Accident Cause'),
        ),
        migrations.AlterField(
            model_name='accd_details',
            name='date',
            field=models.DateTimeField(verbose_name='Date and Time'),
        ),
    ]
