# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 05:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0007_auto_20170929_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_details',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
