# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0008_emp_details_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='manhours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=30, verbose_name='Unit Name')),
                ('date', models.DateField(verbose_name='Date')),
                ('manhours_worked', models.BigIntegerField(verbose_name='Manhours Worked')),
                ('mandays_lost', models.IntegerField(verbose_name='Man-Days Lost')),
            ],
            options={
                'verbose_name_plural': 'Manhours Details',
            },
        ),
    ]
