# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 23:32
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0009_manhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='manhours',
            name='ltifr',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='manhours',
            name='rltifr',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
        migrations.AddField(
            model_name='manhours',
            name='severity_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10),
        ),
    ]
