# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0010_auto_20171004_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manhours',
            name='ltifr',
        ),
        migrations.RemoveField(
            model_name='manhours',
            name='rltifr',
        ),
        migrations.RemoveField(
            model_name='manhours',
            name='severity_rate',
        ),
    ]
