# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-06 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InputForms', '0011_auto_20171005_0828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manhours',
            name='manhours_worked',
        ),
        migrations.AddField(
            model_name='manhours',
            name='manhours_worked_contract',
            field=models.BigIntegerField(default=0, verbose_name='Manhours Worked Contract'),
        ),
        migrations.AddField(
            model_name='manhours',
            name='manhours_worked_regular',
            field=models.BigIntegerField(default=0, verbose_name='Manhours Worked Regular'),
        ),
    ]
